BEGIN TRANSACTION;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
    user_id SERIAL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(22) UNIQUE NOT NULL,
    CONSTRAINT PK_user PRIMARY KEY (user_id)
);

COMMIT TRANSACTION;